### PR TITLE
Oya code

### PR DESCRIPTION
**Pull request by oyadier**

### CODE REVIEW

**Review by oyadier — COMMENTED** [review]
Clean

**Review by oyadier — COMMENTED** [review]
Done deleting all .o files

**Review by KeitaForCode — APPROVED** [review]
seen

**Comment by oyadier** [comment]
doneee

**Review by KeitaForCode — APPROVED** [review]
Done

**Comment by KeitaForCode** [comment]
Wendo

**Review by KeitaForCode — APPROVED** [review]

**Review by KeitaForCode — APPROVED** [review]

**Review by KeitaForCode — APPROVED** [review]

**Pull request closed without merging**
